---
- name: Install Docker to AMI
  hosts: default
  gather_facts: true
  become: true

  tasks:
  - name: Add Docker's official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker's apt repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      state: present

  - name: Update and upgrade apt packages
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Docker package
    apt:
      name: docker-ce
      state: present

  - name: Enable Docker service
    service:
      name: docker
      enabled: yes
      state: started

  - name: Install pip
    pip:
      name: docker